# Generated by Django 3.2.6 on 2023-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='documento',
            field=models.IntegerField(unique=True),
        ),
    ]
